name: jbet88
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  flutter_rating_bar: ^4.0.1
  gradient_borders: ^1.0.1
  flutter_svg_provider: ^1.0.7
  country_pickers: ^3.0.1
  responsive_grid_list: ^1.4.0
  carousel_slider_plus: ^7.1.0
  smooth_page_indicator: ^1.2.0+3
  timelines_plus: ^1.0.4
  fl_chart: ^0.70.0
  calendar_date_picker2: ^1.1.8
  qr_flutter: ^4.1.0
  flutter_staggered_grid_view: ^0.7.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Lilita One
      fonts: 
        - asset: assets/fonts/LilitaOne.ttf
          weight: 400
    - family: Noto Sans
      fonts: 
        - asset: assets/fonts/NotoSansBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Calistoga
      fonts: 
        - asset: assets/fonts/CalistogaRegular.ttf
          weight: 400
