import 'package:flutter/material.dart';
import 'package:equatable/equatable.dart';
import '../../../core/app_export.dart';
import '../models/gridslot_one_item_model.dart';
import '../models/listlv1_one_item_model.dart';
import '../models/vip_daily_salary_daily_wage_rules_model.dart';
part 'vip_daily_salary_daily_wage_rules_event.dart';
part 'vip_daily_salary_daily_wage_rules_state.dart';

/// A bloc that manages the state of a VipDailySalaryDailyWageRules according to the event that is dispatched to it.
class VipDailySalaryDailyWageRulesBloc
    extends
        Bloc<
          VipDailySalaryDailyWageRulesEvent,
          VipDailySalaryDailyWageRulesState
        > {
  VipDailySalaryDailyWageRulesBloc(
    VipDailySalaryDailyWageRulesState initialState,
  ) : super(initialState) {
    on<VipDailySalaryDailyWageRulesInitialEvent>(_onInitialize);
  }

  _onInitialize(
    VipDailySalaryDailyWageRulesInitialEvent event,
    Emitter<VipDailySalaryDailyWageRulesState> emit,
  ) async {
    emit(
      state.copyWith(
        vipDailySalaryDailyWageRulesModelObj: state
            .vipDailySalaryDailyWageRulesModelObj
            ?.copyWith(
              gridslotOneItemList: fillGridslotOneItemList(),
              listlv1OneItemList: fillListlv1OneItemList(),
            ),
      ),
    );
  }

  List<GridslotOneItemModel> fillGridslotOneItemList() {
    return [
      GridslotOneItemModel(
        slotOne: ImageConstant.img10733643587,
        slotTwo: "lbl_slot".tr,
      ),
      GridslotOneItemModel(
        slotOne: ImageConstant.img736x36,
        slotTwo: "lbl_fish2".tr,
      ),
      GridslotOneItemModel(
        slotOne: ImageConstant.img536x36,
        slotTwo: "lbl_bingo2".tr,
      ),
      GridslotOneItemModel(
        slotOne: ImageConstant.img636x36,
        slotTwo: "lbl_sport".tr,
      ),
      GridslotOneItemModel(
        slotOne: ImageConstant.img136x36,
        slotTwo: "lbl_live".tr,
      ),
      GridslotOneItemModel(
        slotOne: ImageConstant.img336x36,
        slotTwo: "lbl_egame".tr,
      ),
      GridslotOneItemModel(
        slotOne: ImageConstant.img236x36,
        slotTwo: "lbl_table".tr,
      ),
    ];
  }

  List<Listlv1OneItemModel> fillListlv1OneItemList() {
    return [
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip1,
        lvone: "lbl_lv_12".tr,
        lv1Three: ImageConstant.imgFolder,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip2,
        lvone: "lbl_lv_22".tr,
        lv1Three: ImageConstant.imgFolderGray80007,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip3,
        lvone: "lbl_lv_32".tr,
        lv1Three: ImageConstant.imgFolderGray80007,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip4,
        lvone: "lbl_lv_42".tr,
        lv1Three: ImageConstant.imgFolderGray80007,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip5,
        lvone: "lbl_lv_5".tr,
        lv1Three: ImageConstant.imgFolderGray80007,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip6,
        lvone: "lbl_lv_6".tr,
        lv1Three: ImageConstant.imgFolderGray80007,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip7,
        lvone: "lbl_lv_7".tr,
        lv1Three: ImageConstant.imgFolderGray80007,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip8,
        lvone: "lbl_lv_8".tr,
        lv1Three: ImageConstant.imgFolderGray80007,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip9,
        lvone: "lbl_lv_9".tr,
        lv1Three: ImageConstant.imgFolderGray80007,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
      Listlv1OneItemModel(
        lv1One: ImageConstant.imgIconVip10,
        lvone: "lbl_lv_10".tr,
        lv1Three: ImageConstant.imgFolderGray80007,
        one: "lbl_13".tr,
        tf: "lbl5".tr,
        thirty: "lbl_30".tr,
        three: "lbl_33".tr,
        threehundred: "lbl_3003".tr,
        one1: "lbl5".tr,
        sevenhundred: "lbl_700".tr,
        thirteen: "lbl_132".tr,
        sevenhundred1: "lbl_700".tr,
        two: "lbl5".tr,
        onethousand: "lbl_10002".tr,
        thirtythree: "lbl_332".tr,
        onethousandOne: "lbl_10002".tr,
        three1: "lbl5".tr,
        tenthousand: "lbl_10000".tr,
        fiftythree: "lbl_532".tr,
        andabove: "msg_10000_and_above".tr,
        sixtythree: "lbl_63".tr,
      ),
    ];
  }
}
